# Introduction to PYTORCH 

 - torch , overall for training nn.model , build model , save model.

In [14]:
import torch
import numpy as np

# torch.Tensor Data type

In [18]:
data   = np.array([[1, 2],[3, 4]])
x_data = torch.tensor(data)


print("-"*50)
print("Orginal Data Shape : ",data.shape)
print("Orignal Data       : ",data)
print("pytorch datatype : " , type(data))

print("-"*50)
print("tensor size      : " , x_data.shape )
print("x_data           : " , x_data )
print("pytorch datatype : " , type(x_data))


--------------------------------------------------
Orginal Data Shape :  (2, 2)
Orignal Data       :  [[1 2]
 [3 4]]
pytorch datatype :  <class 'numpy.ndarray'>
--------------------------------------------------
tensor size      :  torch.Size([2, 2])
x_data           :  tensor([[1, 2],
        [3, 4]])
pytorch datatype :  <class 'torch.Tensor'>


 - can also use torch.from_numpy(x_data)  to transform data from numpy type to tensor

# Manipulate torch.Tensor Data

In [19]:
x_zeros = torch.zeros_like(x_data) # retains the properties of x_data
print(f"Zeros Tensor: \n {x_zeros} \n")

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6856, 0.2126],
        [0.4126, 0.8637]]) 



# Create Torch array,matrix data 
    - np.ones(()) , np.random.normal() , np.zeros(()) ,... etc

In [22]:
shape = (3,3)

normal_tensor = torch.normal(mean=0 , std=1 , size=shape)
rand_tensor   = torch.rand(shape) # Unifrom 0 ~ 1 
ones_tensor   = torch.ones(shape)
zeros_tensor  = torch.zeros(shape)

print(f"Noraml Tensor:\n{normal_tensor}\n")
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Noraml Tensor:
tensor([[-0.0828,  0.7248, -0.7038],
        [-0.7661,  0.4850,  0.9788],
        [-2.2625,  0.6992, -0.5345]])

Random Tensor: 
 tensor([[0.6708, 0.4158, 0.2844],
        [0.0370, 0.2010, 0.7121],
        [0.1477, 0.6845, 0.2905]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


# Select tensor specific row , columns
    - Not Different with Numpy array

In [26]:
tensor = torch.rand(4, 4)
print("Orignal Data : \n",tensor,"\n")

print('First row    : '  ,tensor[0,:,]       )
print("Last  row    : "  , tensor[-1,:,]     )
print('First Column : '  , tensor[:, 0]      )
print('Last  Column : '  , tensor[:, -1]     )


Orignal Data : 
 tensor([[0.2116, 0.9745, 0.0575, 0.9105],
        [0.4598, 0.3210, 0.6346, 0.6752],
        [0.6235, 0.9090, 0.2560, 0.3001],
        [0.8233, 0.3745, 0.5069, 0.9479]]) 

First row    :  tensor([0.2116, 0.9745, 0.0575, 0.9105])
Last  row    :  tensor([0.8233, 0.3745, 0.5069, 0.9479])
First Column :  tensor([0.2116, 0.4598, 0.6235, 0.8233])
Last  Column :  tensor([0.9105, 0.6752, 0.3001, 0.9479])


# Horizon Concat & Vertical Concat tensor

In [31]:
hstack = torch.cat([tensor, tensor], dim=1)
vstack = torch.cat([tensor, tensor], dim=0)

print("horizon concat  : \n",hstack,'\n')
print("vertical concat : \n",vstack)

horizon concat  : 
 tensor([[0.2116, 0.9745, 0.0575, 0.9105, 0.2116, 0.9745, 0.0575, 0.9105],
        [0.4598, 0.3210, 0.6346, 0.6752, 0.4598, 0.3210, 0.6346, 0.6752],
        [0.6235, 0.9090, 0.2560, 0.3001, 0.6235, 0.9090, 0.2560, 0.3001],
        [0.8233, 0.3745, 0.5069, 0.9479, 0.8233, 0.3745, 0.5069, 0.9479]]) 

vertical concat : 
 tensor([[0.2116, 0.9745, 0.0575, 0.9105],
        [0.4598, 0.3210, 0.6346, 0.6752],
        [0.6235, 0.9090, 0.2560, 0.3001],
        [0.8233, 0.3745, 0.5069, 0.9479],
        [0.2116, 0.9745, 0.0575, 0.9105],
        [0.4598, 0.3210, 0.6346, 0.6752],
        [0.6235, 0.9090, 0.2560, 0.3001],
        [0.8233, 0.3745, 0.5069, 0.9479]])


# Tensor Computation

In [46]:
tensor = torch.rand(2, 2)
print(f"tensor matix  :\n{tensor}\n")


# Inner Product can be like 
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# Element by Element Mutliplication
z1 = tensor * tensor
z2 = tensor.mul(tensor)

print("-"*15+"Inner Product"+"-"*25)
print(f"pytorch @ multiplier  : \n{y1}\n")
print(f"pytorch tensor.matmul : \n{y2}\n")

print("-"*15+"Element by Element"+"-"*25)
print(f"pytorch * multiplier : \n{z1}\n")
print(f"pytorch mul : \n{z2}\n")

tensor matix  :
tensor([[0.9887, 0.9977],
        [0.5682, 0.6638]])

---------------Inner Product-------------------------
pytorch @ multiplier  : 
tensor([[1.9730, 1.2241],
        [1.2241, 0.7635]])

pytorch tensor.matmul : 
tensor([[1.9730, 1.2241],
        [1.2241, 0.7635]])

---------------Element by Element-------------------------
pytorch * multiplier : 
tensor([[0.9775, 0.9955],
        [0.3229, 0.4407]])

pytorch mul : 
tensor([[0.9775, 0.9955],
        [0.3229, 0.4407]])



# Tensor Aggregate

In [50]:
agg_sum  = tensor.sum()
agg_item = agg_sum.item() # call the values behind it 

print(f"sum of \n{tensor}\n")
print(agg_item, type(agg_item))

sum of 
tensor([[0.9887, 0.9977],
        [0.5682, 0.6638]])

3.218458652496338 <class 'float'>


In [51]:
print(tensor, "\n")
tensor.add_(5)

print(tensor)

tensor([[0.9887, 0.9977],
        [0.5682, 0.6638]]) 

tensor([[5.9887, 5.9977],
        [5.5682, 5.6638]])


In [52]:
tensor + 5 

tensor([[10.9887, 10.9977],
        [10.5682, 10.6638]])

In [53]:
tensor

tensor([[5.9887, 5.9977],
        [5.5682, 5.6638]])